#define BOOT_LOADER_HEADER_SIZE					0x200
#define BOOT_LOADER_HEADER_SIZE_OFFSET			0x44
#define BOOT_LOADER_HEADER_LOADADDR_OFFSET		0x48
#define BOOT_LOADER_HEADER_LAUNCHADDR_OFFSET	0x4C
#define BOOT_LOADER_HEADER_BOOTMETHOD_OFFSET	0x57
#define BOOT_LOADER_HEADER_NSIH_OFFSET			(BOOT_LOADER_HEADER_SIZE-4)
#define BOOT_LOADER_LOADADDR_DEFAULT			(0xffff0000)
#define BOOT_LOADER_LAUNCHADDR_DEFAULT			(0xffff0000)
#define BOOT_LOADER_MAX_SIZE					(50 * 1024)
#define BOOT_LOADER_HEADER_NSIH					(0x4849534e)

static const char BOOT_METHODS[][6] = {
    "USB", "SPI", "NAND", "SDMMC", "SDFS"
};